baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Frontier'
theme = "hugo-bearcub"
copyright = "Licensed under CC BY-NC 4.0"
[params]
madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
description = "LOL .Everything you need to know about the three languages."
[languages]
  [languages.en]
    languageName = 'EN'
    weight = 6
  [languages.vi]
    languageName = 'VI'
    weight = 7
   [languages.vi.params]  
    description = "101 bài code thiếu nhi."
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 3

[[languages.vi.menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4

[[languages.vi.menu.main]]
  name = "Liên lạc"
  url = "/contact/"
  weight = 4

[[menu.main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 5