baseURL = 'https://cookiezmonst.github.io/webpage/'
languageCode = 'en-us'
title = 'Frontier'
theme = "hugo-bearcub"
copyright = "Licensed under CC BY-NC 4.0"
[params]
madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
description = "Enlish format."
[languages]
  [languages.en]
    languageName = 'EN'
    weight = 6
  [languages.vi]
    languageName = 'VI'
    weight = 7
   [languages.vi.params]  
    description = "Vietnamese format."
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[languages.vi.menu.main]]
  name = "Tường nhà"
  url = "/vi/"
  weight = 1

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 2

[[languages.vi.menu.main]]
  name = "Services"
  url = "/vi/services/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 3

[[languages.vi.menu.main]]
  name = "Blog"
  url = "/vi/posts/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4

[[languages.vi.menu.main]]
  name = "Liên lạc"
  url = "/vi/contact/"
  weight = 4

[[menu.main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 5

[[languages.vi.menu.main]]
  name = "Thư viện"
  url = "/vi/gallery/"
  weight = 5